// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// EMERGENCY FALLBACK: Use hardcoded values if env vars not available
// This is needed because Lovable may not load .env files properly
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://ujjjuoqqefgtrpecneeg.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqamp1b3FxZWZndHJwZWNuZWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MDc1MjksImV4cCI6MjA3OTM4MzUyOX0.7P7VSlbs01-UDOJf5Zo49j0rEWwUMFmjf-V9qWMe2wA';

console.log('🔧 Supabase Client Init:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  keyLength: SUPABASE_PUBLISHABLE_KEY?.length,
  envUrl: import.meta.env.VITE_SUPABASE_URL,
  envKey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
});

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables!\n\n' +
    'Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY\n' +
    'in your environment variables or .env file.\n\n' +
    'For Lovable: Go to Settings > Environment Variables'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});